### ISSUE TITLE
SearXNG for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/searxng-startos#20]
### Service: SearXNG

**Current Status:**
- [ ] Works Fine
- [ ] Partial Issues
- [ ] Doesn't Work

**Description:**
SearXNG needs to be tested in StartOS 0.3.6 to ensure it functions as expected. The current observations are:
- Basic functionality appears to work.

**Tasks:**
- [ ] Perform in-depth testing on SearXNG.
- [ ] Investigate and resolve any health check issues.
- [ ] Confirm full compatibility with StartOS 0.3.6.
